routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('user/{id?}', 'UserController@show')->name('users.show');



Route::get('magic/{user}', 'UserController@superMagicAwesomeLookup')->name('users.magic-show');


Route::get('nathans_page', function () {
	phpinfo();
	// return view('nathanspage');
})->name('nathan');

// Wire up all resource routes in one go!
// see: https://laravel.com/docs/5.3/controllers#resource-controllers
Route::resource('posts', 'PostController');


Route::get('api/v1/users/{user}/posts', 'UserController@posts')->name('users.posts');


















Route::get('/', function () {
	
    return view('welcome');
});








// route to display an index page of all cars!
Route::get('cars', function () {

	// retrieve the set of cars, that the view should show!
	$cars = 
	[
		new App\Car('Toyota'),
		new App\Car('Audi')
	];

	$title = "Car Shoowroom";

	// want all comments
	$comments = App\Comment::all();

	// return the view - controller decides the view!!!
	return view('cars', compact('cars', 'title', 'comments'));


});


Route::get('questions/{id}/{slug}', function ($name, $foo) {
	return 'Yoo ' . $name . $foo;
});

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    public function __construct($make)
    {
    	$this->make = $make;
    }
}

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    // link it with the related user model
    public function user() 
    {
    	return $this->hasMany('App\User');
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = 
    [ 
    	'user_id',
    	'description',
    	'title'
    ];

    public function user()
    {
    	return $this->belongsTo('App\User');
    }

    public function doThing()
    {
    	return 1 * 2;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    // Ensure that the URL is included in this model's JSON
    protected $appends = [
        'url'
    ];


    // declare the 'url' as a dynamic attribute
    // get<nameOfAttribute>Attribute
    public function getUrlAttribute() {
        return route('users.show', $this->id);
    }

    public function posts()
    {
        return $this->hasMany('App\Post');
    }

    public function getPostsApiUrlAttribute()
    {
        return route('users.posts', $this->id);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Post;
use App\User;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Post::all();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    { 
        // 1. Validate the data
        $this->validate($request, [
            'title' => 'required|min:2|max:80',
            'description' => 'required|min:1|max:16000'
        ]);

        // 2. Extract form data
        $values = $request->only('title', 'description');


        // 3. Write to the DB
        User::first()->posts()->create($values);

        // 4. view?
        return redirect()->route('nathan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return $post;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

use App\Http\Requests;

// role of controle code, to:
// 1. Receive HTTP request
// 2. Decide which models to extract / manipulate
// 3. Decide what view to return, & pass models (or data) to that view to present
class UserController extends Controller
{

	// action (method in controller that handles 
	// HTTP request) to show a particular user profile
    public function show($id = -1)
    {
		$user = User::find($id);
		return view('demo', compact('user'));
    }

    public function superMagicAwesomeLookup(User $user)
    {
    	return view('demo', compact('user'));
    }


    // function to return the JSON representation of a given users posts
    public function posts(User $user)
    {
        return $user->posts;
    }
}

resources/views/cars.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway';
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            
            <h1>
                {{ $title }}
            </h1>

            @foreach($cars as $car)
                <p>
                    {{ $car->make }}
                </p>
            @endforeach

            
            <!-- Show all comments -->
            @foreach($comments as $comment)

                <h2>
                    {{ $comment->id }} : {{ $comment->text }}
                    <p>
                        Posted by: {{ $comment->user->username }}
                    </p>
                </h2>

            @endforeach

        </div>
    </body>
</html>

resources/views/demo.blade.php
@extends('layouts.master')

@section('content')

	<!-- Page content -->
	<h1>This page show user details</h1>
	<p>User details are important for users</p>

	@include('widgets.user-info')

	<div class="posts">
		
	</div>
@stop


@section('scripts')
	<script>
		// hit the users' post route and alert what i get back!
		var updatePosts = function () {

			// issue an AJAX request to the server, to load the posts in
			$.get('{{ $user->postsApiUrl }}', function (posts) {
				// here because the AJAX, background web request has completed!
				// posts is an array of posts!

				// display them!
				var $postsContainer = $('.posts');
				$postsContainer.empty();

				// loop over each post, and display it!
				for(var i=0; i<posts.length; i++) 
				{
					var currentPost = posts[i];

					// niave approach to client-side templating
					// you may want to investigate:
					// - handlebars.js
					// - vue.js
					// - angular.js
					// - look up client-side templating
					$postsContainer.append('<p>Title: ' + currentPost.title + '</p>');
				}
			});
		};

		// immediately update the posts so we don't have to wait 3 seconds...
		updatePosts();

		// cause the update to occur every 3000 seconds
		window.setInterval(updatePosts, 3000);

	</script>
@stop

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    

    <div class="container">
        <br>
        <br>
        <br>
        <br>
        @section('content')

        @show
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>

    <!-- Load custom JS file -->
    <script src="/js/test.js"></script>

    @yield('scripts')
    
  </body>
</html>

resources/views/nathanspage.blade.php
<!DOCTYPE html>
<html>
<head>
    <title> Nathans Page! </title>
</head>
<body>

    <h1>My Name is Nathan!</h1>

    <h2>I teach people php, bootstrap and laravel.</h2>


</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.master')

@section('content')

	<form class="form-horizontal" action="{{ route('posts.store') }}" method="post">

		<!-- ensure that the form can pass CSRF protection -->
		<input type="hidden" name="_token" value="{{ csrf_token() }}">

		<div class="form-group">
			<label for="title" class="col-sm-2 control-label">Title</label>
			<div class="col-sm-10">
			  <input name="title" type="text" class="form-control" id="title" placeholder="Title...">
			</div>
		</div>

		<div class="form-group">
			<label for="description" class="col-sm-2 control-label">Description</label>
			<div class="col-sm-10">
			  <input name="description" type="text" class="form-control" id="description" placeholder="Description">
			</div>
		</div>
	
		<div class="form-group">
			<div class="col-sm-10 col-sm-offset-2">
				<button class="btn btn-primary">Create!</button>
			</div>
		</div>

	</form>

@stop

resources/views/user-profile.blade.php
<html>
	<body>
		<h1>User profile {{ $id }}</h1>

		<a href="{{ $user->url }}">
			Click this to get to this same page!!!
		</a>
		
		<p>
			{{ $user->name }} is {{ $user->age }} years old.
		</p>
	</body>
</html>

resources/views/widgets/user-info.blade.php
<!-- a small, reusable bit of html to show some user data -->

<div class="user-info">
	<h3>Name: {{ $user->name }}</h3>
	<h3>Id: {{ $user->id }}</h3>
	<h3>Url: {{ $user->url }}</h3>
</div>